const KEY='ashley_life_os_v11_pages';
const OLD=['ashley_life_os_v11','ashley_life_os_v10'];
const $=id=>document.getElementById(id),uid=()=>Math.random().toString(36).slice(2,9),today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=n=>'$'+(Number(n)||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}):'';
const base=()=>({version:'11-pages',tab:'dashboard',tasks:[],events:{},brain:[],home:[],meals:{},grocery:[],lincoln:{routine:[],notes:[],potty:[],toys:[],books:[],clothes:[]},expenses:[],bills:[],inventory:[],weekly:{},lastBackup:''});
let S;
function normalize(x){let b=base();x=x&&typeof x==='object'?x:{};return {...b,...x,events:x.events||{},tasks:x.tasks||[],brain:x.brain||[],home:x.home||x.maintenance||[],meals:x.meals||x.mealPlan||{},grocery:x.grocery||[],expenses:x.expenses||[],bills:x.bills||[],inventory:x.inventory||[],weekly:x.weekly||{},lincoln:{...b.lincoln,...(x.lincoln||{})}}}
function load(){let raw=localStorage.getItem(KEY);if(!raw){for(const k of OLD){raw=localStorage.getItem(k);if(raw)break}}try{S=normalize(raw?JSON.parse(raw):base())}catch{S=base()}save()}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function toast(m){let t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
const tabs=[['dashboard','Today'],['calendar','Calendar'],['tasks','Tasks'],['cleaning','Home'],['meals','Food'],['lincoln','Lincoln'],['finances','Money'],['more','More']];
function renderTabs(){$('tabs').innerHTML=tabs.map(([id,n])=>`<button class="tab ${S.tab===id?'active':''}" onclick="go('${id}')">${n}</button>`).join('')}
function go(id){S.tab=id;document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');renderTabs();render(id);save();scrollTo(0,0)}
function clock(){let d=new Date();$('dateText').textContent=d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});$('timeText').textContent=d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
setInterval(clock,1000);
function dueTasks(){let t=today();return S.tasks.filter(x=>!x.done&&(!x.due||x.due<=t)).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'))}
function todayEvents(){return (S.events[today()]||[]).sort((a,b)=>(a.time||'').localeCompare(b.time||''))}
function nextAction(){let a=dueTasks()[0];if(a)return {title:a.title,meta:a.due&&a.due<today()?'Overdue task':'Task for today'};let e=todayEvents()[0];if(e)return{title:e.title,meta:e.time||'Today'};let h=S.home.find(x=>!x.done);if(h)return{title:h.title,meta:'Home'};return{title:'Capture what is on your mind',meta:'Start small'}}
function dashboard(){let n=nextAction(),ds=dueTasks().slice(0,3),ev=todayEvents().slice(0,3),g=S.grocery.filter(x=>!x.done).length,spent=S.expenses.filter(x=>(x.date||'').slice(0,7)===today().slice(0,7)).reduce((a,x)=>a+Number(x.amount||0),0);$('dashboard').innerHTML=`<div class="now-card"><div class="label">Do this next</div><div class="now-title">${esc(n.title)}</div><div class="now-meta">${esc(n.meta)}</div><div class="acts"><button class="btn gold" onclick="openQuickCapture()">+ Capture</button><button class="btn secondary" onclick="overwhelm()">I'm overwhelmed</button></div></div><div class="grid grid2" style="margin-top:14px"><div class="card"><div class="between"><div class="label">Today's 3</div><button class="btn secondary sm" onclick="go('tasks')">All tasks</button></div>${ds.length?ds.map((x,i)=>`<div class="smart-row"><div class="smart-num">${i+1}</div><div><b>${esc(x.title)}</b><div class="small">${x.due?fmt(x.due):'No due date'}</div></div></div>`).join(''):'<p class="muted">Nothing urgent. Add only what truly matters.</p>'}</div><div class="card"><div class="label">Schedule</div>${ev.length?ev.map(x=>`<div class="smart-row"><div><b>${esc(x.time||'Anytime')}</b><div class="small">${esc(x.title)}</div></div></div>`).join(''):'<p class="muted">No calendar items today.</p>'}</div></div><div class="hub-grid" style="margin-top:14px"><button class="hub" onclick="go('cleaning')"><strong>Home</strong><span>${S.home.filter(x=>!x.done).length} open home items</span></button><button class="hub" onclick="go('meals')"><strong>Food</strong><span>${g} groceries waiting</span></button><button class="hub" onclick="go('lincoln')"><strong>Lincoln</strong><span>Routine, notes, potty, toys & books</span></button><button class="hub" onclick="go('finances')"><strong>Money</strong><span>${money(spent)} spent this month</span></button></div>`}
function tasks(){let list=[...S.tasks].sort((a,b)=>(a.done-b.done)||((a.due||'9999').localeCompare(b.due||'9999')));$('tasks').innerHTML=`<div class="between"><div><div class="label">Tasks</div><div class="h2">One trusted list</div></div><button class="btn" onclick="taskModal()">+ Task</button></div><div class="card" style="margin-top:14px">${list.length?list.map(x=>`<div class="item ${x.done?'done':''}"><div class="row"><input class="check" type="checkbox" ${x.done?'checked':''} onchange="toggleTask('${x.id}')"><div style="flex:1"><div class="it-t">${esc(x.title)}</div><div class="it-m">${x.due?fmt(x.due)+' · ':''}${esc(x.category||'Life')}</div></div></div><div class="acts"><button class="iconbtn" onclick="deleteTask('${x.id}')">Delete</button></div></div>`).join(''):'<p class="muted">No tasks yet.</p>'}</div>`}
function taskModal(){modal('Add task',`<input class="inp" id="qTitle" placeholder="What needs to happen?"><div class="fg" style="margin-top:9px"><input class="inp" id="qDue" type="date" value="${today()}"><select id="qCat"><option>Life</option><option>Home</option><option>Lincoln</option><option>Money</option><option>Work</option><option>Health</option></select></div>`,()=>{let v=$('qTitle').value.trim();if(!v)return;S.tasks.push({id:uid(),title:v,due:$('qDue').value,category:$('qCat').value,done:false});save();closeModal();tasks();toast('Task added')})}
function toggleTask(id){let x=S.tasks.find(x=>x.id===id);if(x)x.done=!x.done;save();render(S.tab)}function deleteTask(id){S.tasks=S.tasks.filter(x=>x.id!==id);save();tasks()}
function calendar(){let t=today(),e=S.events[t]||[];$('calendar').innerHTML=`<div class="between"><div><div class="label">Calendar</div><div class="h2">Today + quick planning</div></div><button class="btn" onclick="eventModal()">+ Event</button></div><div class="card" style="margin-top:14px"><div class="label">${fmt(t)}</div>${e.length?e.map(x=>`<div class="item"><div class="between"><div><div class="it-t">${esc(x.time||'Anytime')} · ${esc(x.title)}</div><div class="it-m">${esc(x.category||'Life')}</div></div><button class="iconbtn" onclick="deleteEvent('${x.id}')">Delete</button></div></div>`).join(''):'<p class="muted">Nothing scheduled today.</p>'}</div><div class="card" style="margin-top:14px"><div class="label">Add another date</div><input id="calDate" type="date" class="inp" value="${t}" onchange="showDate(this.value)"><div id="dateEvents" style="margin-top:10px"></div></div>`;showDate(t)}
function showDate(d){let z=$('dateEvents');if(!z)return;let e=S.events[d]||[];z.innerHTML=e.length?e.map(x=>`<div class="item"><div class="it-t">${esc(x.time||'Anytime')} · ${esc(x.title)}</div></div>`).join(''):'<p class="muted">No events.</p>'}
function eventModal(){modal('Add event',`<input id="eTitle" class="inp" placeholder="Event"><div class="fg" style="margin-top:9px"><input id="eDate" type="date" class="inp" value="${today()}"><input id="eTime" type="time" class="inp"><select id="eCat" class="full"><option>Life</option><option>Lincoln</option><option>Home</option><option>Work</option><option>Health</option></select></div>`,()=>{let v=$('eTitle').value.trim(),d=$('eDate').value;if(!v)return;(S.events[d]??=[]).push({id:uid(),title:v,time:$('eTime').value,category:$('eCat').value});save();closeModal();calendar();toast('Event added')})}
function deleteEvent(id){for(let d in S.events)S.events[d]=S.events[d].filter(x=>x.id!==id);save();calendar()}
function cleaning(){let open=S.home.filter(x=>!x.done);$('cleaning').innerHTML=`<div class="between"><div><div class="label">Home</div><div class="h2">Reset, don't perfect</div></div><button class="btn" onclick="homeModal()">+ Home item</button></div><div class="grid grid2" style="margin-top:14px"><div class="card"><div class="label">Open</div>${open.length?open.map(x=>homeRow(x)).join(''):'<p class="muted">Home list is clear.</p>'}</div><div class="card"><div class="label">Fast reset</div>${['Start one load of laundry','Clear kitchen sink','10-minute floor pickup','Bathroom wipe-down','Take out trash'].map(x=>`<button class="btn secondary" style="width:100%;margin:4px 0" onclick="quickHome('${x}')">${x}</button>`).join('')}</div></div><div class="card" style="margin-top:14px"><div class="between"><div class="label">Declutter + inventory</div><button class="btn secondary sm" onclick="inventoryModal()">+ Item</button></div>${S.inventory.length?S.inventory.map(x=>`<div class="item"><div class="between"><div><div class="it-t">${esc(x.name)}</div><div class="it-m">${esc(x.category)} · ${esc(x.decision)}</div></div><button class="iconbtn" onclick="delInventory('${x.id}')">Delete</button></div></div>`).join(''):'<p class="muted">Track toys, books, clothes, pantry, freezer and household items here.</p>'}</div>`}
function homeRow(x){return`<div class="item ${x.done?'done':''}"><label class="row"><input class="check" type="checkbox" onchange="toggleHome('${x.id}')"><div><div class="it-t">${esc(x.title||x.name)}</div><div class="it-m">${esc(x.room||x.type||'Home')}</div></div></label></div>`}
function homeModal(){modal('Add home item',`<input id="hTitle" class="inp" placeholder="What needs attention?"><select id="hRoom" style="margin-top:9px"><option>Kitchen</option><option>Living room</option><option>Bathroom</option><option>Bedroom</option><option>Laundry</option><option>Car</option><option>Outside</option><option>Other</option></select>`,()=>{let v=$('hTitle').value.trim();if(!v)return;S.home.push({id:uid(),title:v,room:$('hRoom').value,done:false});save();closeModal();cleaning()})}
function quickHome(title){S.home.push({id:uid(),title,room:'Reset',done:false});save();cleaning();toast('Added')}
function toggleHome(id){let x=S.home.find(x=>x.id===id);if(x)x.done=!x.done;save();cleaning()}
function inventoryModal(){modal('Add inventory item',`<input id="iName" class="inp" placeholder="Item"><div class="fg" style="margin-top:9px"><select id="iCat"><option>Toys</option><option>Books</option><option>Clothes</option><option>Pantry</option><option>Freezer</option><option>Household</option></select><select id="iDecision"><option>Keep</option><option>Rotate</option><option>Store</option><option>Donate</option><option>Sell</option><option>Undecided</option></select></div>`,()=>{let v=$('iName').value.trim();if(!v)return;S.inventory.push({id:uid(),name:v,category:$('iCat').value,decision:$('iDecision').value});save();closeModal();cleaning()})}
function delInventory(id){S.inventory=S.inventory.filter(x=>x.id!==id);save();cleaning()}
function meals(){let d=today(),m=S.meals[d]||{};$('meals').innerHTML=`<div class="between"><div><div class="label">Food</div><div class="h2">Meals + groceries</div></div><button class="btn" onclick="mealModal()">Plan today</button></div><div class="grid grid2" style="margin-top:14px"><div class="card"><div class="label">Today</div>${['Breakfast','Lunch','Dinner','Snack'].map(k=>`<div class="item"><div class="it-t">${k}</div><div class="it-m">${esc(m[k.toLowerCase()]||'Not planned')}</div></div>`).join('')}</div><div class="card"><div class="between"><div class="label">Grocery list</div><button class="btn secondary sm" onclick="groceryModal()">+ Add</button></div>${S.grocery.length?S.grocery.map(x=>`<div class="item ${x.done?'done':''}"><label class="row"><input class="check" type="checkbox" ${x.done?'checked':''} onchange="toggleGrocery('${x.id}')"><span class="it-t">${esc(x.text)}</span></label></div>`).join(''):'<p class="muted">Nothing on the list.</p>'}</div></div>`}
function mealModal(){let m=S.meals[today()]||{};modal('Plan today',`<input id="mb" class="inp" placeholder="Breakfast" value="${esc(m.breakfast||'')}"><input id="ml" class="inp" placeholder="Lunch" style="margin-top:8px" value="${esc(m.lunch||'')}"><input id="md" class="inp" placeholder="Dinner" style="margin-top:8px" value="${esc(m.dinner||'')}"><input id="ms" class="inp" placeholder="Snack" style="margin-top:8px" value="${esc(m.snack||'')}">`,()=>{S.meals[today()]={breakfast:$('mb').value,lunch:$('ml').value,dinner:$('md').value,snack:$('ms').value};save();closeModal();meals()})}
function groceryModal(){modal('Add grocery',`<input id="gItem" class="inp" placeholder="Milk, berries, chicken...">`,()=>{let v=$('gItem').value.trim();if(!v)return;S.grocery.push({id:uid(),text:v,done:false});save();closeModal();meals()})}
function toggleGrocery(id){let x=S.grocery.find(x=>x.id===id);if(x)x.done=!x.done;save();meals()}
function lincoln(){let L=S.lincoln;$('lincoln').innerHTML=`<div><div class="label">Lincoln</div><div class="h2">One kid hub</div><p class="muted">Routine, preschool, potty, toys, books, clothes, health and memories.</p></div><div class="hub-grid" style="margin-top:14px">${[['Routine','routine'],['Potty','potty'],['Toys','toys'],['Books','books'],['Clothes','clothes'],['Notes + memories','notes']].map(([n,k])=>`<button class="hub" onclick="lincolnAdd('${k}','${n}')"><strong>${n}</strong><span>${(L[k]||[]).length} saved</span></button>`).join('')}</div><div class="card" style="margin-top:14px"><div class="label">Recent</div>${Object.entries(L).flatMap(([k,a])=>(Array.isArray(a)?a.map(x=>({...x,k})):[])).slice(-12).reverse().map(x=>`<div class="item"><div class="it-t">${esc(x.text||x.title||x.name)}</div><div class="it-m">${esc(x.k)}${x.date?' · '+fmt(x.date):''}</div></div>`).join('')||'<p class="muted">No notes yet.</p>'}</div>`}
function lincolnAdd(k,n){modal('Lincoln · '+n,`<textarea id="lText" placeholder="Add ${n.toLowerCase()} note..."></textarea>`,()=>{let v=$('lText').value.trim();if(!v)return;(S.lincoln[k]??=[]).push({id:uid(),text:v,date:today()});save();closeModal();lincoln();toast('Saved')})}
function finances(){let ym=today().slice(0,7),ex=S.expenses.filter(x=>(x.date||'').startsWith(ym)),spent=ex.reduce((a,x)=>a+Number(x.amount||0),0);$('finances').innerHTML=`<div class="between"><div><div class="label">Money</div><div class="h2">Simple household view</div></div><button class="btn" onclick="expenseModal()">+ Expense</button></div><div class="srow" style="margin-top:14px"><div class="sbox"><div class="sl">Spent this month</div><div class="sv">${money(spent)}</div></div><div class="sbox"><div class="sl">Bills</div><div class="sv">${S.bills.length}</div></div></div><div class="grid grid2"><div class="card"><div class="label">Recent expenses</div>${ex.slice(-12).reverse().map(x=>`<div class="item"><div class="between"><div><div class="it-t">${esc(x.name)}</div><div class="it-m">${fmt(x.date)} · ${esc(x.category)}</div></div><b>${money(x.amount)}</b></div></div>`).join('')||'<p class="muted">No expenses logged this month.</p>'}</div><div class="card"><div class="between"><div class="label">Bills</div><button class="btn secondary sm" onclick="billModal()">+ Bill</button></div>${S.bills.map(x=>`<div class="item"><div class="between"><div><div class="it-t">${esc(x.name)}</div><div class="it-m">Due day ${x.day||'—'}</div></div><b>${money(x.amount)}</b></div></div>`).join('')||'<p class="muted">No bills added.</p>'}</div></div>`}
function expenseModal(){modal('Log expense',`<input id="xName" class="inp" placeholder="What did you spend on?"><div class="fg" style="margin-top:9px"><input id="xAmount" class="inp" type="number" inputmode="decimal" placeholder="Amount"><input id="xDate" class="inp" type="date" value="${today()}"><select id="xCat" class="full"><option>Groceries</option><option>Dining</option><option>Gas</option><option>Shopping</option><option>Lincoln</option><option>Health</option><option>Home</option><option>Personal</option><option>Other</option></select></div>`,()=>{let v=$('xName').value.trim();if(!v)return;S.expenses.push({id:uid(),name:v,amount:Number($('xAmount').value||0),date:$('xDate').value,category:$('xCat').value});save();closeModal();finances()})}
function billModal(){modal('Add bill',`<input id="bName" class="inp" placeholder="Bill name"><div class="fg" style="margin-top:9px"><input id="bAmount" class="inp" type="number" placeholder="Amount"><input id="bDay" class="inp" type="number" min="1" max="31" placeholder="Due day"></div>`,()=>{let v=$('bName').value.trim();if(!v)return;S.bills.push({id:uid(),name:v,amount:Number($('bAmount').value||0),day:$('bDay').value});save();closeModal();finances()})}
function more(){$('more').innerHTML=`<div><div class="label">More</div><div class="h2">Tools, not clutter</div></div><div class="hub-grid" style="margin-top:14px"><button class="hub" onclick="brainModal()"><strong>Brain Dump</strong><span>${S.brain.length} captured</span></button><button class="hub" onclick="weeklyReset()"><strong>Weekly Reset</strong><span>Walk through the essentials</span></button><button class="hub" onclick="searchModal()"><strong>Search</strong><span>Find anything in your OS</span></button><button class="hub" onclick="backup()"><strong>Backup</strong><span>Save a copy to Files/iCloud</span></button><button class="hub" onclick="restoreModal()"><strong>Restore</strong><span>Import a Life OS JSON backup</span></button><button class="hub" onclick="go('dashboard')"><strong>Back to Today</strong><span>Return to what matters now</span></button></div><div class="safety" style="margin-top:14px"><b>Data safety:</b> this free GitHub Pages version stores your private data on this device in your browser. Export a backup regularly.</div>`}
function brainModal(){modal('Brain dump',`<textarea id="brainText" placeholder="Dump it here. You do not have to organize it yet."></textarea>`,()=>{let v=$('brainText').value.trim();if(!v)return;S.brain.push({id:uid(),text:v,date:today()});save();closeModal();toast('Captured')})}
function weeklyReset(){let items=['Check calendar for next 7 days','Choose only 3 weekly priorities','Laundry + towels','Bathroom reset','Floors + main living area','Fridge check + meal plan','Build grocery list','Review bills due','Prep Lincoln schedule/bag','Choose one thing just for you'];let w=S.weekly[today()]||{};modal('Weekly reset',`<p class="muted" style="margin-bottom:10px">Must-do first. Nice-to-do only if you have capacity.</p>${items.map((x,i)=>`<label class="reset-item"><input class="check" type="checkbox" ${w[i]?'checked':''} onchange="weeklyCheck(${i},this.checked)"><div><b>${esc(x)}</b><span>${i<8?'Must do':'Nice to do'}</span></div></label>`).join('')}`,null,'Done')}
function weeklyCheck(i,v){(S.weekly[today()]??={})[i]=v;save()}
function searchModal(){modal('Search Life OS',`<input id="searchQ" class="inp" placeholder="Search tasks, notes, groceries, inventory..." oninput="runSearch(this.value)"><div id="searchResults" class="search-results"></div>`,null,'Close')}
function runSearch(q){q=q.trim().toLowerCase();let out=[];if(q){S.tasks.forEach(x=>x.title.toLowerCase().includes(q)&&out.push(['Task',x.title]));S.brain.forEach(x=>x.text.toLowerCase().includes(q)&&out.push(['Brain',x.text]));S.grocery.forEach(x=>x.text.toLowerCase().includes(q)&&out.push(['Grocery',x.text]));S.inventory.forEach(x=>(x.name+' '+x.category+' '+x.decision).toLowerCase().includes(q)&&out.push(['Inventory',x.name]));Object.entries(S.events).forEach(([d,a])=>a.forEach(x=>x.title.toLowerCase().includes(q)&&out.push(['Calendar '+d,x.title])))}$('searchResults').innerHTML=out.slice(0,30).map(x=>`<div class="item"><div class="it-t">${esc(x[1])}</div><div class="it-m">${esc(x[0])}</div></div>`).join('')||'<p class="muted">No matches yet.</p>'}
function overwhelm(){let a=dueTasks().slice(0,2).map(x=>x.title);if(a.length<3){let h=S.home.find(x=>!x.done);if(h)a.push(h.title||h.name)}while(a.length<3)a.push(['Drink water and eat something simple','Clear one visible surface','Start one laundry load'][a.length]);modal("I'm overwhelmed",`<div class="mode-banner"><div class="label">Only these three</div>${a.slice(0,3).map((x,i)=>`<div class="smart-row"><div class="smart-num">${i+1}</div><b>${esc(x)}</b></div>`).join('')}<p class="muted" style="margin-top:10px">Everything else can wait until these are done.</p></div>`,null,'Okay')}
function openQuickCapture(){modal('Capture anything',`<select id="qcType"><option>Task</option><option>Event</option><option>Grocery</option><option>Expense</option><option>Brain dump</option><option>Lincoln note</option><option>Home item</option></select><input id="qcText" class="inp" style="margin-top:9px" placeholder="Type it here..."><input id="qcExtra" class="inp" style="margin-top:9px" placeholder="Amount or time (optional)">`,()=>{let type=$('qcType').value,v=$('qcText').value.trim(),x=$('qcExtra').value;if(!v)return;if(type==='Task')S.tasks.push({id:uid(),title:v,due:today(),category:'Life',done:false});if(type==='Event')(S.events[today()]??=[]).push({id:uid(),title:v,time:x,category:'Life'});if(type==='Grocery')S.grocery.push({id:uid(),text:v,done:false});if(type==='Expense')S.expenses.push({id:uid(),name:v,amount:Number(x||0),date:today(),category:'Other'});if(type==='Brain dump')S.brain.push({id:uid(),text:v,date:today()});if(type==='Lincoln note')S.lincoln.notes.push({id:uid(),text:v,date:today()});if(type==='Home item')S.home.push({id:uid(),title:v,room:'Home',done:false});save();closeModal();render(S.tab);toast('Captured')})}
function modal(title,body,onSave,close='Cancel'){$('MT').textContent=title;$('MB').innerHTML=body;$('MA').innerHTML=(onSave?`<button class="btn gold" id="saveModal">Save</button>`:'')+`<button class="btn secondary" onclick="closeModal()">${close}</button>`;if(onSave)$('saveModal').onclick=onSave;$('MO').classList.add('open');setTimeout(()=>$('MO').querySelector('input,textarea,select')?.focus(),50)}
function closeModal(){$('MO').classList.remove('open')}function cm(){closeModal()}function cmo(e){if(e.target===$('MO'))closeModal()}
async function backup(){let data=JSON.stringify(S,null,2),file=new File([data],`life-os-backup-${today()}.json`,{type:'application/json'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Life OS backup'});S.lastBackup=new Date().toISOString();save();return}}catch{}let a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;a.click();S.lastBackup=new Date().toISOString();save();toast('Backup saved')}
function restoreModal(){modal('Restore backup',`<input id="restoreFile" type="file" accept="application/json,.json" class="inp"><p class="muted" style="margin-top:8px">This replaces the data currently stored in this browser.</p>`,()=>{let f=$('restoreFile').files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{S=normalize(JSON.parse(r.result));save();closeModal();renderAll();toast('Backup restored')}catch{alert('That backup file could not be read.')}};r.readAsText(f)})}
function render(id){({dashboard,tasks,calendar,cleaning,meals,lincoln,finances,more}[id]||dashboard)()}
function renderAll(){renderTabs();tabs.forEach(([id])=>{if(id===S.tab)$(id).classList.add('active');else $(id).classList.remove('active')});render(S.tab);clock()}
load();renderAll();
