const days=[
{d:'Mon',date:'Aug 17',focus:'Lower A',home:'Laundry + quick floors',lincoln:'Color Hunt',workout:['Treadmill warm-up · 5–10 min','Leg press · 3×12 @ 120 lb','Hip abduction · 3×15 @ 80 lb','Hip adduction · 3×10–12 @ 45 lb','Glute kickbacks · 3×10–12/side @ 50 lb','Leg extension · 3×12 @ 40 lb','Optional incline walk · 5–10 min'],meals:[['Breakfast','Bakery-Style Egg Bites','egg'],['Lunch','Planned meal — recipe will be added in Sunday planning',''],['Snack','Greek yogurt + fruit',''],['Dinner','Planned meal — recipe will be added in Sunday planning','']]},
{d:'Tue',date:'Aug 18',focus:'Upper A + walk',home:'Bathroom wipe-down',lincoln:'Sticker + shape sort',workout:['Upper A workout','Walking finish'],meals:[['Breakfast','Bakery-Style Egg Bites','egg'],['Lunch','Leftovers / protein lunch',''],['Snack','Simple protein snack',''],['Dinner','Pork Fried Rice','pork']]},
{d:'Wed',date:'Aug 19',focus:'Recovery + mobility',home:'Meal prep + pet care',lincoln:'Outdoor water painting',workout:['Recovery + mobility'],meals:[['Breakfast','Baked Apple Cinnamon Oatmeal','oats'],['Lunch','Leftovers',''],['Snack','Simple snack',''],['Dinner','Planned meal — recipe will be added in Sunday planning','']]},
{d:'Thu',date:'Aug 20',focus:'Lower B',home:'Put laundry away',lincoln:'Dance + freeze',workout:['Lower B · glutes + hamstrings'],meals:[['Breakfast','Loaded Veggie Frittata','frittata'],['Lunch','Protein lunch',''],['Snack','Simple snack',''],['Dinner','Steak Salad with Chimichurri','steak']]},
{d:'Fri',date:'Aug 21',focus:'Upper B + core',home:'Friday home reset',lincoln:'Play-Doh fine motor',workout:['Upper B + core-safe work'],meals:[['Breakfast','Bakery-Style Egg Bites','egg'],['Lunch','Leftover Steak Salad','steak'],['Snack','Simple snack',''],['Dinner','Planned meal — recipe will be added in Sunday planning','']]},
{d:'Sat',date:'Aug 22',focus:'Optional walk',home:'One focused home block',lincoln:'Outdoor scavenger hunt',workout:['Optional walk / recovery'],meals:[['Breakfast','Flexible family breakfast',''],['Lunch','Leftovers / easy lunch',''],['Snack','Optional',''],['Dinner','Flexible dinner','']]},
{d:'Sun',date:'Aug 23',focus:'Recovery + reset',home:'Groceries + weekly reset',lincoln:'Kitchen helper',workout:['Recovery + weekly planning'],meals:[['Breakfast','Easy breakfast',''],['Lunch','Leftovers',''],['Snack','Optional',''],['Dinner','Meal-prep-friendly dinner','']]}
];
const recipes={
egg:{ingredients:['6 large eggs','1/2 cup cottage cheese','1/4 cup milk','1/2 tsp salt','1/4 tsp black pepper','1 cup mix-ins: bacon, sautéed spinach, shredded cheese, or roasted red peppers'],directions:['Heat oven to 325°F and grease a muffin tin.','Blend eggs, cottage cheese, milk, salt and pepper until smooth.','Divide mix-ins among cups and pour egg mixture to about 3/4 full.','Place muffin tin in a larger baking dish; add hot water halfway up the muffin tin sides.','Bake 20–25 minutes until set. Cool 5 minutes and release.'],prep:'Prep mix-ins up to 2 days ahead. Refrigerate up to 5 days or freeze cooled bites up to 2 months. Microwave frozen 60–90 sec; refrigerated 30–45 sec.'},
pork:{ingredients:['3 tbsp oil, divided','2 eggs, beaten','1 lb cooked pork, diced','1 onion, diced','2 carrots, diced small','1 cup frozen peas','3 garlic cloves, minced','4 cups cold day-old cooked rice','3 tbsp soy sauce','1 tsp toasted sesame oil','Green onion'],directions:['Scramble eggs in 1 tbsp oil; remove from pan.','Add remaining oil, pork, onion and carrots; stir-fry 5–6 minutes.','Add peas and garlic; cook 1 minute.','Add cold rice; stir-fry 4–5 minutes.','Return eggs; add soy sauce and sesame oil. Top with green onion.'],prep:'Cold day-old rice is important. Cook extra rice ahead. Refrigerate leftovers up to 4 days or freeze up to 2 months.'},
steak:{ingredients:['1 cup parsley','1/4 cup cilantro','3 garlic cloves','1/3 cup olive oil','3 tbsp red wine vinegar','1/2 tsp red pepper flakes','Salt + pepper','2 lb flank or skirt steak','8 cups mixed greens','1 cup cherry tomatoes, halved','1/2 red onion, thinly sliced','1/2 cup feta or blue cheese'],directions:['Pulse parsley, cilantro, garlic, olive oil, vinegar and red pepper flakes until finely chopped; season.','Season steak and grill over high heat 4–5 minutes per side for medium-rare.','Rest 5–10 minutes; slice against the grain.','Build salad with greens, tomatoes, onion and cheese.','Top with steak and chimichurri.'],prep:'Chimichurri can be made up to 3 days ahead. Refrigerate leftover steak up to 3 days; serve cold or room temperature over salad.'},
oats:{ingredients:['2 cups old-fashioned oats','1/3 cup brown sugar','1 1/2 tsp baking powder','1 tsp cinnamon','1/2 tsp salt','2 cups milk','1 egg','3 tbsp melted butter','1 tsp vanilla','2 apples, peeled and diced','Cinnamon sugar topping'],directions:['Heat oven to 375°F and grease a 9×9 dish.','Whisk dry ingredients together.','Whisk milk, egg, melted butter and vanilla separately.','Layer half the apples, oat mixture, wet mixture and remaining apples; top with cinnamon sugar.','Bake 35–40 minutes; rest 5 minutes.'],prep:'Dry and wet mixtures can be prepared separately the night before.'},
frittata:{ingredients:['8 eggs','1/4 cup milk','1/2 tsp salt','1/4 tsp pepper','2 tbsp olive oil or butter','1 cup diced bell peppers','1 cup spinach or kale','1/2 cup onion','1 cup cherry tomatoes, halved','3/4 cup shredded cheese'],directions:['Heat oven to 375°F. Whisk eggs, milk, salt and pepper.','Sauté onion and peppers 4–5 minutes.','Add spinach and tomatoes for 1–2 minutes.','Pour in egg mixture and cook 2 minutes. Add cheese.','Bake 12–15 minutes; rest 5 minutes.'],prep:'Chop vegetables up to 2 days ahead. Refrigerate up to 4 days or freeze slices up to 1 month.'}}
let tab='today'; const key='myWeekStateV1'; let state=JSON.parse(localStorage.getItem(key)||'{}');
const save=()=>localStorage.setItem(key,JSON.stringify(state));
function check(id,label){const v=!!state[id];return `<label class="row"><input type="checkbox" data-id="${id}" ${v?'checked':''}><span>${label}</span></label>`}
function recipeCard(name,k,id){if(!k)return `<div class="card meal">${check(id,name)}</div>`;let r=recipes[k];return `<div class="card meal">${check(id,name)}<details><summary>Ingredients</summary><ul>${r.ingredients.map(x=>`<li>${x}</li>`).join('')}</ul></details><details><summary>Directions</summary><ol>${r.directions.map(x=>`<li>${x}</li>`).join('')}</ol></details><details><summary>Prep / Reheat</summary><p>${r.prep}</p></details></div>`}
function today(){const x=days[0],ids=[];x.workout.forEach((_,i)=>ids.push('m-w'+i));x.meals.forEach((_,i)=>ids.push('m-meal'+i));ids.push('m-home','m-linc','grat1','grat2','grat3','top1','top2','top3');let done=ids.filter(i=>state[i]).length,p=Math.round(done/ids.length*100);return `<div class="hero"><div><div class="eyebrow">MONDAY · AUG 17</div><h1>My Day</h1></div><div class="pill">${done}/${ids.length} done</div></div><div class="card"><div class="small">TODAY</div><div class="progress"><div style="width:${p}%"></div></div><div class="small" style="margin-top:7px">${p}% complete</div></div><h2 class="section-title">🏋️ Workout · ${x.focus}</h2><div class="card">${x.workout.map((a,i)=>check('m-w'+i,a)).join('')}</div><h2 class="section-title">🍽️ Meals + Recipes</h2>${x.meals.map((m,i)=>recipeCard(m[0]+' · '+m[1],m[2],'m-meal'+i)).join('')}<h2 class="section-title">🏠 Home</h2><div class="card">${check('m-home',x.home)}</div><h2 class="section-title">👩‍👦 Lincoln</h2><div class="card">${check('m-linc',x.lincoln)}<p class="small">Find red, blue, yellow and green objects around the house.</p></div><h2 class="section-title">🧠 Mind + Spirit</h2><div class="card"><p><b>Journal:</b> What would make me proud of how I handled today, even if I don’t finish everything?</p><textarea id="journal" class="journal" placeholder="Write a few thoughts…">${state.journal||''}</textarea><p><b>Gratitude</b></p>${check('grat1','Someone I love')}${check('grat2','Something my body can do')}${check('grat3','One ordinary thing that makes life better')}<p class="small"><b>2–5 minute reset:</b> Take 5 slow breaths. Ask for patience, clarity and gratitude. Sit quietly for 1–2 minutes.</p></div><h2 class="section-title">⭐ Your 3</h2><div class="card">${check('top1','Lower A workout')}${check('top2','Laundry + floors')}${check('top3','Color Hunt with Lincoln')}</div><div class="quote">“Success is the sum of small efforts, repeated day in and day out.”</div>`}
function week(){return `<div class="hero"><div><div class="eyebrow">AUG 17–23</div><h1>My Week</h1></div></div><div class="day-grid">${days.map(x=>`<div class="day"><strong>${x.d}<br><span class="small">${x.date}</span></strong><span class="tag">${x.focus}</span><p class="small"><b>Home</b><br>${x.home}</p><p class="small"><b>Lincoln</b><br>${x.lincoln}</p></div>`).join('')}</div><h2 class="section-title">Meals</h2>${days.map((x,di)=>`<div class="card"><b>${x.d}</b>${x.meals.map((m,i)=>`<div class="row"><span>${m[0]} · ${m[1]}</span></div>`).join('')}</div>`).join('')}`}
function calendar(){return `<div class="hero"><div><div class="eyebrow">WEEK VIEW</div><h1>Calendar</h1></div></div><div class="calendar-list">${days.map(x=>`<div class="card"><b>${x.d} · ${x.date}</b><p>${x.focus}</p><p class="small">🏠 ${x.home}<br>👩‍👦 ${x.lincoln}</p></div>`).join('')}</div>`}
function render(){document.getElementById('app').innerHTML=tab==='today'?today():tab==='week'?week():calendar();document.querySelectorAll('[data-id]').forEach(el=>el.onchange=e=>{state[e.target.dataset.id]=e.target.checked;save();render()});let j=document.getElementById('journal');if(j)j.oninput=e=>{state.journal=e.target.value;save()};document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});render();